### ISSUE TITLE
Want to open popup on single click 

### ISSUE THREAD

**Issue by WaqarAhmadGit** [juliomarcos/ImageViewPopUpHelper#2]
Hello i used your jar library in my project but it opens image on double click and i want to open it on single click kindly help me.
Waiting for your response.
Thanks

**Comment by juliomarcos** [comment]
this is not supported.
but you could modify the `imageView.setOnClickListener(...` to use another event listener.

**Comment by WaqarAhmadGit** [comment]
Kindly guide me little bit about that will be much appreciated.
